#!/usr/bin/env python3
"""Concatenate the per-release keycode-change files for a QMK migration window.

The keycode catalog is split one-file-per-release under
references/keycodes-changelog/ (e.g. 0.25.0.md). To migrate a keymap from version
S to version T you need every release r with  S < r <= T. This tool collects
exactly those files and prints them as a single document, so an agent (or human)
reads the whole migration window at once instead of opening each file by hand —
which is error-prone when the window spans many releases.

Usage:
  scripts/keycodes_migration.py --from 0.22.0 --to 0.30.0
  scripts/keycodes_migration.py --from 0.25.0            # --to defaults to latest
  scripts/keycodes_migration.py --from 0.22.0 --list     # just list the files
  scripts/keycodes_migration.py --from 0.22.0 -o out.md  # write to a file
  scripts/keycodes_migration.py --from 0.22.0 --include-cosmetic

The window is half-open: a release r is included iff  from < r <= to.
'latest' resolves to the newest cataloged release. Releases whose only changes
are cosmetic (copyright bumps / clang-format whitespace) are skipped by default;
pass --include-cosmetic to keep them.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_CATALOG = os.path.normpath(
    os.path.join(HERE, os.pardir, "references", "keycodes-changelog"))

VER_RE = re.compile(r"^\d+\.\d+\.\d+$")
# Machine-readable marker the generator writes at the top of each per-version file:
#   <!-- qmk-keycodes: version=0.23.3 semantic=false -->
MARK_RE = re.compile(r"qmk-keycodes:\s*version=([0-9.]+)\s+semantic=(true|false)")


def vt(s):
    return tuple(int(x) for x in s.split("."))


def discover(catalog_dir):
    """Sorted list of versions that have a <version>.md file in catalog_dir."""
    out = []
    for fn in os.listdir(catalog_dir):
        if fn.endswith(".md") and VER_RE.match(fn[:-3]):
            out.append(fn[:-3])
    return sorted(set(out), key=vt)


def is_semantic(path):
    """True if the release has at least one non-cosmetic keycode change.

    Reads the generator's marker first (cheap, exact); falls back to scanning the
    leading text for the 'No semantic keycode change' note if the marker is absent."""
    with open(path, encoding="utf-8") as f:
        head = f.read(4096)
    m = MARK_RE.search(head)
    if m:
        return m.group(2) == "true"
    return "No semantic keycode change" not in head and "No semantic keycode changes" not in head


def build_header(src, to, window, skipped):
    L = []
    w = L.append
    w("# QMK keycode migration dump")
    w("")
    w(f"<sub>Window `{src}` → `{to}` · {len(window)} release(s) included · "
      f"generated by `scripts/keycodes_migration.py`</sub>")
    w("")
    w(f"To migrate a keymap from **{src}** to **{to}**, apply every "
      f"`deprecated OLD→NEW` and `retired OLD` entry across the releases below "
      f"(the half-open interval `({src}, {to}]`). `added` entries are informational "
      f"and need no action; `removed` entries need deletion or substitution.")
    w("")
    w("> **Change-kind legend:**")
    w("> - `deprecated OLD→NEW` — OLD still compiles via `quantum_keycodes_legacy.h` "
      "but is on a removal timer; **rename to NEW now**.")
    w("> - `retired OLD` — the legacy shim was deleted; OLD no longer compiles. Replace "
      "with the **NEW** named at the release where it was *deprecated*.")
    w("> - `removed` — feature/keycode deleted entirely; no replacement. Delete or substitute.")
    w("> - `added` — new options available. Informational only; not a migration requirement.")
    w("")
    w("The exact edit list = `{OLD names in your keymap.c}` ∩ "
      "`{OLD names deprecated/retired/removed below}`.")
    w("")
    w("**Releases in this dump:**")
    for v in window:
        w(f"- `{v}`")
    if skipped:
        w("")
        w(f"<sub>{len(skipped)} cosmetic-only release(s) in this window were skipped: "
          f"{', '.join(skipped)} (pass `--include-cosmetic` to include them).</sub>")
    w("")
    w("---")
    w("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser(
        description="Concatenate per-release keycode-change files for a QMK "
                    "migration window (from, to].",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="The window is half-open: a release r is included iff from < r <= to. "
               "'latest' resolves to the newest cataloged release. Cosmetic-only "
               "releases (copyright/whitespace) are skipped unless --include-cosmetic "
               "is given.")
    ap.add_argument("--from", required=True, dest="src", metavar="VERSION",
                    help="Current QMK version (exclusive lower bound). Need not have its own file.")
    ap.add_argument("--to", default="latest", dest="dst", metavar="VERSION|latest",
                    help="Target QMK version, inclusive upper bound, or 'latest' (default: latest).")
    ap.add_argument("--catalog-dir", default=DEFAULT_CATALOG,
                    help=f"Directory of per-version files (default: {DEFAULT_CATALOG})")
    ap.add_argument("--include-cosmetic", action="store_true",
                    help="Include copyright/whitespace-only releases (skipped by default).")
    ap.add_argument("--list", action="store_true",
                    help="Only list the release files in the window; do not concatenate.")
    ap.add_argument("-o", "--output", default=None, metavar="FILE",
                    help="Write the concatenated dump here instead of stdout.")
    args = ap.parse_args()

    if not VER_RE.match(args.src):
        sys.exit(f"error: --from '{args.src}' is not a valid version (expected N.N.N, e.g. 0.22.0).")
    if not os.path.isdir(args.catalog_dir):
        sys.exit(f"error: catalog directory not found: {args.catalog_dir}\n"
                 f"       (run scripts/gen_keycode_catalog.py first, or pass --catalog-dir).")

    versions = discover(args.catalog_dir)
    if not versions:
        sys.exit(f"error: no per-version files found in {args.catalog_dir}.")

    latest = versions[-1]
    if args.dst == "latest":
        to = latest
    else:
        to = args.dst
        if not VER_RE.match(to):
            sys.exit(f"error: --to '{args.dst}' is not a valid version or 'latest'.")

    src_t, to_t = vt(args.src), vt(to)
    if to_t > vt(latest):
        print(f"warning: --to '{to}' is newer than the latest cataloged release "
              f"'{latest}'; clamping to '{latest}'.", file=sys.stderr)
        to, to_t = latest, vt(latest)
    if to_t <= src_t:
        sys.exit(f"error: target '{to}' must be newer than --from '{args.src}'. "
                 "Nothing to migrate in an empty or negative window.")

    window = [v for v in versions if src_t < vt(v) <= to_t]

    skipped = []
    if not args.include_cosmetic:
        kept = []
        for v in window:
            if is_semantic(os.path.join(args.catalog_dir, f"{v}.md")):
                kept.append(v)
            else:
                skipped.append(v)
        window = kept

    if args.list:
        print(f"Migration window ({args.src}, {to}] — {len(window)} release(s) to read:")
        for v in window:
            print(f"  {v}.md")
        if skipped:
            print(f"\nSkipped {len(skipped)} cosmetic-only release(s): {', '.join(skipped)}")
            print("(pass --include-cosmetic to include them.)")
        if not window:
            print("\nNo semantic keycode changes in this window — nothing to migrate.")
        return 0

    if not window:
        msg = f"No semantic keycode changes in ({args.src}, {to}] — nothing to migrate."
        if skipped:
            msg += (f"\n({len(skipped)} cosmetic-only release(s) were skipped; "
                    "pass --include-cosmetic to see them.)")
        print(msg, file=sys.stderr)
        return 0

    out = [build_header(args.src, to, window, skipped)]
    for v in window:
        with open(os.path.join(args.catalog_dir, f"{v}.md"), encoding="utf-8") as f:
            out.append(f.read().rstrip())
        out.append("\n---\n")
    text = "\n".join(out).rstrip() + "\n"

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(text)
        print(f"Wrote {args.output} ({len(window)} releases, {len(text)} bytes).",
              file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())